project:
  type: website
  output-dir: docs

website:
  # title: "Home"
  favicon: assets/logo.png
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    logo: assets/logo.png
    background: dark
    collapse: true
    left:
      - text: "{{< fa solid house >}}home"
        href: index.qmd
      - text: "{{< fa layer-group >}}blog"
        href: blog.qmd
      - text: "{{< fa mug-saucer >}} Support Me"
        href: https://www.buymeacoffee.com/edwardxiong
    right:
      - text: "{{< fa address-card >}}About Me"
        href: about.qmd
      - icon: github
        href: https://github.com/EdwardShiung
      - icon: linkedin
        href: https://www.linkedin.com/in/tian-yu-edward-shiung-1b4639289/

  sidebar:
    style: "docked"
    pinned: true
    collapse-level: 1
    contents:
      - section: "Statistics"
        contents: posts/Probability Theory/**
      - section: "Machine Learning"
      - section: "Deep Learning"
      - section: "NLP"
      - section:  "Computer Vision"

  page-footer:
    center: "© Copyright 2023 Tian Yu Shiung"
    right:
      - icon: github
        href: https://github.com/EdwardShiung

format:
  html:
    reference-location: document
    theme:
      light: sandstone
      dark: [cyborg, custom.scss]
    css: styles.css
    toc: true
